name: bd-action
run-name: Blackduck-scan-${{github.actor}}-${{github.sha}}
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - "master"
env: 
  BLACKDUCK_URL: https://apus-blackduck.volvocars.biz
  BLACKDUCK_PROJECT_NAME: function-dispatcher               
  BLACKDUCK_PROJECT_VERSION:  0.1.0                       
  BLACKDUCK_ACCESS_TOKEN: ${{secrets.BLACKDUCK_API_TOKEN}} 


jobs:
  BlackDuckScan: 
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Black Duck Full Scan
        run: |
          bash <(curl -s -L https://detect.blackduck.com/detect9.sh) \
          --blackduck.url=$BLACKDUCK_URL \
          --blackduck.api.token=$BLACKDUCK_ACCESS_TOKEN \
          --blackduck.trust.cert=true \
          --detect.project.name=$BLACKDUCK_PROJECT_NAME \
          --detect.project.version.name=$BLACKDUCK_PROJECT_VERSION  \
          --detect.source.path=./include \
          --detect.accuracy.required=NONE \
          --detect.project.version.distribution=INTERNAL
 