name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ cmake

      - name: Configure with CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Run unit tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Run examples
        run: |
          cd build/example
          ./async_call
          ./complex_type
          ./detaching
          ./events
          ./reference
          ./safety
          ./same_signature
          ./timer
          ./expect