name: Generate Doxygen Documentation

on:
  push:
    branches:
      - master

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Doxygen
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz

      # Generate Doxygen documentation
      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html